### ISSUE TITLE
RVC_2_Training error generate and error splitting on WebUi

### ISSUE THREAD

**Issue by Trainne** [ardha27/AI-Song-Cover-RVC#17]
I got " --- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 30, in <module>
    from infer.modules.uvr5.modules import uvr
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer/modules/uvr5/modules.py", line 13, in <module>
    config = Config()
  File "/content/Retrieval-based-Voice-Conversion-WebUI/configs/config.py", line 34, in wrapper
    wrapper.instance = func(*args, **kwargs)
  File "/content/Retrieval-based-Voice-Conversion-WebUI/configs/config.py", line 58, in _init_
    self.x_pad, self.x_query, self.x_center, self.x_max = self.device_config()
  File "/content/Retrieval-based-Voice-Conversion-WebUI/configs/config.py", line 121, in device_config
    logger.info("Found GPU", self.gpu_name)
Message: 'Found GPU " 
I Try to run audio split on webui cannot work and try to generate ai cover with other sample wav got error.
![2](https://github.com/ardha27/AI-Song-Cover-RVC/assets/143859508/4f20820f-6a09-4ac3-934a-014a6f987738)
![1](https://github.com/ardha27/AI-Song-Cover-RVC/assets/143859508/dc2e3b69-2050-46a0-8efb-40201d0a2390)

**Comment by MinatoIsuki** [comment]
Interesting...
I will recheck this soon, for now please try RVC V2 by ardha instead.

**Comment by MinatoIsuki** [comment]
I've patch it in my repo, can you try click on my notebook on ardha readme and try again to see any errors left?

**Comment by ardha27** [comment]
<img width="287" alt="image" src="https://github.com/ardha27/AI-Song-Cover-RVC/assets/48845217/28f6ac00-df0f-42f5-a81a-66c8ee9434aa">
i think this was the issue, i already change its

**Comment by MinatoIsuki** [comment]
> <img alt="image" width="287" src="https://user-images.githubusercontent.com/48845217/265180802-28f6ac00-df0f-42f5-a81a-66c8ee9434aa.png"> i think this was the issue, i already change its

It is, but its my notebook though 😭

**Comment by Trainne** [comment]
Great job, for generate now this fixed and worked, but for spilitting still don't work at link ardha and Minatolsuki.
![3](https://github.com/ardha27/AI-Song-Cover-RVC/assets/143859508/18107661-225b-45e8-9977-49fa8dd98733)

**Comment by MinatoIsuki** [comment]
> Great job, for generate now this fixed and worked, but for spilitting still don't work at link ardha and Minatolsuki. ![3](https://user-images.githubusercontent.com/143859508/265184854-18107661-225b-45e8-9977-49fa8dd98733.png)

Looks like audio_path should be path_audio. Let's see about that.

**Comment by Trainne** [comment]
yea, I did as usual entering the link /content/Drive/Mydrive/audio

**Comment by MinatoIsuki** [comment]
> yea, I did as usual entering the link /content/Drive/Mydrive/audio

Were you using WebUI to seperate?

**Comment by Trainne** [comment]
yea, i use WebUI, cause this a simple to bulk spilitting

**Comment by MinatoIsuki** [comment]
> yea, i use WebUI, cause this a simple to bulk spilitting

That sucks.
I've use splitting script just for a single voice sample, nevel deal with this.
I will try to fix this (if I can 🙂)

**Comment by Trainne** [comment]
I hope I can, if not, at least I can do it one by one on webui :),
because previously it was very easy, I'm addicted to it hahaha

**Comment by MinatoIsuki** [comment]
So, I decided to change drive_path to path_audio. Can you retry with this notebook?
If it don't, I give up. (I'm travelling and I'm literally using my grandpa's phone to edit the notebook 😅)

https://colab.research.google.com/drive/1AQBcDadXTpm8IhwpJA48zVR7BxPWxuwF

**Comment by Trainne** [comment]
same issue, I've tried one and bulk and the message that comes out is still the same, but it's okay at least the generate can work, thank you for trying :") , enjoy traveling Cao..
