### ISSUE TITLE
Error saat ingin convert Inferencing 

### ISSUE THREAD

**Issue by Reno121** [ardha27/AI-Song-Cover-RVC#2]
bang pas saya convert error terus 

```
Traceback (most recent call last):
  
File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1323, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1257, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 2531, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py", line 163, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py", line 177, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'
Traceback (most recent call last):
  File "/content/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 146, in vc_single
    if_f0 = cpt.get("f0", 1)
NameError: name 'cpt' is not defined

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1323, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1257, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 2531, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py", line 163, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py", line 177, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'
```

**Comment by ardha27** [comment]
Kirim ssnya

**Comment by Reno121** [comment]
![RVC_Training ipynb - Colaboratory - Google Chrome 5_16_2023 8_49_14 AM](https://github.com/ardha27/AI-Song-Cover-RVC/assets/89187695/d4f973c4-96bb-43c8-92c6-70c6ecc75535)
![RVC_Training ipynb - Colaboratory - Google Chrome 5_16_2023 8_50_39 AM](https://github.com/ardha27/AI-Song-Cover-RVC/assets/89187695/79930b88-acde-476a-be7d-827b001738b3)

**Comment by ardha27** [comment]
Itu inferencing timbrenya masih kosong

**Comment by Reno121** [comment]
Lah iya ga nyadar wkwkwk, langsung saya close aja
