### ISSUE TITLE
Error when create ai cover

### ISSUE THREAD

**Issue by Hyllite** [ardha27/AI-Song-Cover-RVC#22]
Traceback (most recent call last):
  File "/content/AICoverGen/src/main.py", line 291, in song_cover_pipeline
    voice_change(voice_model, main_vocals_dereverb_path, ai_vocals_path, pitch_change, f0_method, index_rate, filter_radius, rms_mix_rate, protect, crepe_hop_length, is_webui)
  File "/content/AICoverGen/src/main.py", line 201, in voice_change
    rvc_infer(rvc_index_path, index_rate, vocals_path, output_path, pitch_change, f0_method, cpt, version, net_g, filter_radius, tgt_sr, rms_mix_rate, protect, crepe_hop_length, vc, hubert_model)
  File "/content/AICoverGen/src/rvc.py", line 150, in rvc_infer
    audio_opt = vc.pipeline(hubert_model, net_g, 0, audio, input_path, times, pitch_change, f0_method, index_path, index_rate, if_f0, filter_radius, tgt_sr, 0, rms_mix_rate, version, protect, crepe_hop_length)
  File "/content/AICoverGen/src/vc_infer_pipeline.py", line 571, in pipeline
    self.vc(
  File "/content/AICoverGen/src/vc_infer_pipeline.py", line 424, in vc
    npy = np.sum(big_npy[ix] * np.expand_dims(weight, axis=2), axis=1)
IndexError: index -1 is out of bounds for axis 0 with size 0

**Comment by MinatoIsuki** [comment]
The value `filter_radius` is currrently `-1`. The only value that is accepted is between 0 to 7.
