### ISSUE TITLE
The Modded AICoverGen (for Colab Free) Broke

### ISSUE THREAD

**Issue by dylan012006** [ardha27/AI-Song-Cover-RVC#37]
The other cells worked fine but "Run WebUI" keeps getting an "ImportError" all of a sudden. What happened?

![image](https://github.com/ardha27/AI-Song-Cover-RVC/assets/61915388/9b4264fc-efdb-42bc-a0f2-98f8cea37074)

**Comment by iyokanmomiji** [comment]
The exact same error occurred with the google colab version of the original aicovergen.

**Comment by shrlckhom** [comment]
Same problem here


/content/RVC
2024-02-09 17:29:08.261611: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-09 17:29:08.261672: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-09 17:29:08.263645: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-09 17:29:08.274990: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-09 17:29:10.172294: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-02-09 17:29:17 | INFO | faiss.loader | Loading faiss with AVX2 support.
2024-02-09 17:29:17 | INFO | faiss.loader | Successfully loaded faiss with AVX2 support.
Traceback (most recent call last):
  File "/content/RVC/app.py", line 19, in <module>
    import gradio as gr
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 37, in <module>
    from gradio_client.documentation import document, set_documentation_group
ImportError: cannot import name 'set_documentation_group' from 'gradio_client.documentation' (/usr/local/lib/python3.10/dist-packages/gradio_client/documentation.py)

**Comment by Ghhutf** [comment]
مرحبا
