### ISSUE TITLE
Problem with EasyGUI

### ISSUE THREAD

**Issue by Sponty2000** [ardha27/AI-Song-Cover-RVC#47]
/content/RVC Traceback (most recent call last): File "/content/RVC/demo.py", line 1, in <module> from original import * File "/content/RVC/original.py", line 8, in <module> from infer.modules.vc.modules import VC File "/content/RVC/infer/modules/vc/modules.py", line 11, in <module> from infer.lib.audio import load_audio, wav2 File "/content/RVC/infer/lib/audio.py", line 2, in <module> import ffmpeg ModuleNotFoundError: No module named 'ffmpeg'

**Comment by Sponty2000** [comment]
Hi, now the error is this:

/content/RVC
Traceback (most recent call last):
  File "/content/RVC/demo.py", line 1, in <module>
    from original import *
  File "/content/RVC/original.py", line 3, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
